export const VICTORY_MESSAGE = 'VOCÊ VENCEU!'
export const DEFEAT_MESSAGE = 'VOCÊ PERDEU!'
export const GAME_MANAGER = 'game'
export const MAX_ERRORS = 5
export const MAX_HINTS = 3
export const SUPPORT_EMAIL = 'guimfontes7@gmail.com'
export const GAME_SETTINGS = 'gameSettings'
export const GAME_STATE = 'gameState'
export const GAME_STATS = 'gameStats'
export const DAY_EPOCH_TIME = 86400000
export const GREEN_TILE = '🟩'
export const RED_TILE = '🟥'
export const WIN_EMOJI = '🎉'
export const LOSE_EMOJI = '😢'
